/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY
	(
	intCustID int NOT NULL,
	intAutomaticReminderCategoryID int NULL,
	LastExecutedDateTime datetime NOT NULL,
	dtNextscheduleTime datetime NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY SET (LOCK_ESCALATION = TABLE)
GO
IF EXISTS(SELECT * FROM dbo.TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY)
	 EXEC('INSERT INTO dbo.Tmp_TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY (intCustID, LastExecutedDateTime, dtNextscheduleTime)
		SELECT intCustID, LastExecutedDateTime, dtNextscheduleTime FROM dbo.TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY WITH (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY
GO
EXECUTE sp_rename N'dbo.Tmp_TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY', N'TBL_AUTOMETIC_REMINDER_SERVICE_HISTORY', 'OBJECT' 
GO
COMMIT
