IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER](
	[intMasterPolicyID] [int] IDENTITY(1,1) NOT NULL,
	[strPolicyName] [nvarchar](1000) NOT NULL,
	[strCategoryName] [nvarchar](100) NOT NULL,
	[bitIsSystemPolicy] [bit] NOT NULL,
	[strPolicyDescription] [nvarchar](2000) NULL,
	[strPolicyType] [varchar](4) NOT NULL,
	[strPolicyFilePath] [nvarchar](2000) NOT NULL,
	[intCreatedByUser] [int] NOT NULL,
	[dtCreateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER] PRIMARY KEY CLUSTERED 
(
	[intMasterPolicyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER_bitIsSystemPolicy]') AND type = 'D')
BEGIN

ALTER TABLE [dbo].[TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER] ADD  CONSTRAINT [DF_TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER_bitIsSystemPolicy]  DEFAULT ((0)) FOR [bitIsSystemPolicy]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER_dtCreateDate]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER] ADD  CONSTRAINT [DF_TBL_AUTOMATIC_BRANDING_POLICY_DEFAULT_MASTER_dtCreateDate]  DEFAULT (getutcdate()) FOR [dtCreateDate]
END
GO


